site:
    title: 纸小墨官方博客
    subtitle: 简洁的静态博客构建工具
    # logo: -/images/avatar.jpg
    limit: 10
    theme: theme
    disqus: somebody
    lang: zh
    url: http://www.inkpaper.io/blog/
    # root: /blog

authors:
    me:
        name: 纸小墨
        intro: 简洁的静态博客构建工具
        avatar: -/images/avatar.jpg

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - theme/bundle
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
